java -Xmx2g -Xms2g rushhour/RushHour random1.txt
java -Xmx2g -Xms2g rushhour/RushHour random2.txt
java -Xmx2g -Xms2g rushhour/RushHour random3.txt
java -Xmx2g -Xms2g rushhour/RushHour random4.txt
java -Xmx2g -Xms2g rushhour/RushHour random5.txt
java -Xmx2g -Xms2g rushhour/RushHour random6.txt
java -Xmx2g -Xms2g rushhour/RushHour random7.txt
java -Xmx2g -Xms2g rushhour/RushHour random8.txt
java -Xmx2g -Xms2g rushhour/RushHour random9.txt
java -Xmx2g -Xms2g rushhour/RushHour random10.txt
java -Xmx2g -Xms2g rushhour/RushHour random11.txt
java -Xmx2g -Xms2g rushhour/RushHour random12.txt